# FastAgent Configuration File

# Default Model Configuration:
#
# Takes format:
#   <provider>.<model_string>.<reasoning_effort?> (e.g. anthropic.claude-3-5-sonnet-20241022 or openai.o3-mini.low)
# Accepts aliases for Anthropic Models: haiku, haiku3, sonnet, sonnet35, opus, opus3
# and OpenAI Models: gpt-4.1, gpt-4.1-mini, o1, o1-mini, o3-mini
#
# If not specified, defaults to "haiku".
# Can be overriden with a command line switch --model=<model>, or within the Agent constructor.

default_model: slow

mcp_timeline:
  steps: 30 # number of timeline buckets to render
  step_seconds: 2 # seconds per bucket (accepts values like "45s", "2m")

# Logging and Console Configuration:
logger:
  # level: "debug" | "info" | "warning" | "error"
  # type: "none" | "console" | "file" | "http"
  # path: "/path/to/logfile.jsonl"

  # Switch the progress display on or off
  progress_display: true

  # Show chat User/Assistant messages on the console
  show_chat: true
  # Show tool calls on the console
  show_tools: true
  # Truncate long tool responses on the console
  truncate_tools: true
  streaming: none

# MCP Servers
mcp:
  servers:
    anon_hf:
      transport: http
      url: http://localhost:3001/mcp
      headers:
        Authorization: Bearer
    test_hf:
      transport: http # DVe0UTvm4
      url: http://localhost:3001/mcp
      implementation:
        name: claude-code
        version: 1.0.62
    test_all_hf:
      transport: http
      url: http://localhost:3001/mcp?bouquet=all
    skybridge:
      transport: http
      url: http://localhost:3001/mcp
      implementation:
        name: openai-mcp
        version: 0.1.0
    live_hf:
      transport: http
      url: https://huggingface.co/mcp
      headers:
        Authorization: Bearer ${HF_TEST_TOKEN}
